org: amalv
app: apollo-lambda
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'} # default to 'local' if no stage is provided
  httpApi:
    cors: true
functions:
  graphql:
    environment:
      NODE_ENV: production
      DB_ENDPOINT: ${param:DB_ENDPOINT, env:DB_ENDPOINT}
      DB_PORT: ${param:DB_PORT, env:DB_PORT}
      DB_NAME: ${param:DB_NAME, env:DB_NAME}
      DB_USERNAME: ${param:DB_USERNAME, env:DB_USERNAME}
      DB_PASSWORD: ${param:DB_PASSWORD, env:DB_PASSWORD}
      DB_SSL_CERT: /var/task/certs/global-bundle.pem
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
configValidationMode: error
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript
custom:
  dotenv:
    path: ./.env.${self:provider.stage}
package:
  include:
    - certs/**
